INSERT INTO interesse (nome) VALUES
('Arquitetura sustentável'),
('Economia'),
('Artesanato'),
('Autossustentabilidade'),
('Segurança digital'),
('Comunicação visual'),
('Viagens'),
('Literatura clássica'),
('Cultura hip-hop'),
('Saúde digital'),
('Ciclismo urbano'),
('Cultura italiana'),
('Cervejas artesanais'),
('Séries de TV'),
('Nutrição'),
('Desafios profissionais'),
('DIY (faça você mesmo)'),
('História da moda'),
('Cultura de consumo'),
('Sociologia'),
('Programação'),
('Futebol feminino'),
('Desenho'),
('Empoderamento feminino'),
('Comida rápida saudável'),
('Tecnologia verde'),
('Cinema'),
('História de vida'),
('Linguística'),
('Inteligência artificial aplicada'),
('Medicina alternativa'),
('Animes'),
('História da fotografia'),
('Cidades inteligentes'),
('Mercado imobiliário'),
('RPGs'),
('Astronautica'),
('Cultura inglesa'),
('Relacionamentos'),
('Antropologia cultural'),
('História da arquitetura'),
('Paternidade'),
('Literatura contemporânea'),
('Tradições indígenas'),
('Estudo de línguas'),
('Marketing pessoal'),
('Futuro da educação'),
('Trabalho remoto'),
('Futebol'),
('Piquenique'),
('Bebidas artesanais'),
('Relações interpessoais'),
('Psicologia'),
('Festas temáticas'),
('Tecnologia educativa'),
('Festas de casamento'),
('Veganismo'),
('Design de produto'),
('Religião'),
('Entretenimento'),
('Fórmula 1'),
('Ecoturismo'),
('Saúde'),
('História da arte'),
('Trabalho voluntário'),
('Design gráfico'),
('Linguagem de sinais'),
('Desenvolvimento de aplicativos'),
('História da música'),
('Futebol americano'),
('Astronomia'),
('Desenvolvimento pessoal'),
('Estudo de idiomas'),
('Tecnologias vestíveis'),
('Cultura de bem-estar'),
('Jornalismo investigativo'),
('Investimentos em startups'),
('Cultura indiana'),
('Diversidade'),
('Gestão de projetos'),
('Fotografia de retratos'),
('Desafios de fotografia'),
('Comida vegetariana'),
('Estilo de vida saudável'),
('Arquitetura paisagística'),
('História'),
('Psicologia social'),
('Fitness'),
('Comida saudável'),
('Design de interiores sustentáveis'),
('Negócios digitais'),
('Liderança'),
('Investimentos sustentáveis'),
('Festas tradicionais'),
('Tradições gastronômicas'),
('Inteligência emocional'),
('Esportes aquáticos'),
('Música eletrônica'),
('Gestão de tempo'),
('Estilo de vida minimalista'),
('Histórias em quadrinhos'),
('Marketing de influência'),
('Segurança cibernética'),
('Fotografia analógica'),
('Literatura de ficção científica'),
('Meditação'),
('Tradições familiares'),
('Medicina esportiva'),
('Saúde preventiva'),
('Ecologia'),
('Tecnologia da informação'),
('Fotografia de paisagens'),
('Psicanálise'),
('Comida regional'),
('Arquitetura'),
('Escrita criativa'),
('Arte'),
('Leitura'),
('Criação de conteúdo'),
('Transporte sustentável'),
('Política internacional'),
('Livros de autoajuda'),
('Networking'),
('Automobilismo'),
('Cultura pop'),
('Antiguidade'),
('Turismo ecológico'),
('Relações públicas'),
('Relações familiares'),
('Sistemas de gerenciamento'),
('Tecnologia blockchain'),
('Comida de rua'),
('Desafios tecnológicos'),
('Arte moderna'),
('Política'),
('Moda'),
('Tendências de moda'),
('Tendências em beleza'),
('Política brasileira'),
('Música gospel'),
('Desafios literários'),
('Artesanato local'),
('Cultura local'),
('Cultura latina'),
('Política pública'),
('Música popular brasileira'),
('Sustentabilidade'),
('Investimentos em criptomoedas'),
('Turismo sustentável'),
('Programação para crianças'),
('Voluntariado'),
('Comércio eletrônico'),
('Marketing social'),
('Moda consciente'),
('Futebol de praia'),
('Carreira profissional'),
('Marketing de conteúdo visual'),
('Voz e canto'),
('Economia criativa'),
('Cultura de rua'),
('Jardinagem'),
('Técnicas de meditação'),
('Viajar pelo mundo'),
('Basquete'),
('Arte de rua'),
('Games de estratégia'),
('Música'),
('Cozinha'),
('Tecnologia de consumo'),
('Documentários'),
('Natação'),
('Música ao vivo'),
('Fotografia de eventos'),
('Cultura africana'),
('Bolsas e acessórios'),
('Carreira no exterior'),
('Maternidade e paternidade'),
('Empreendedorismo'),
('Startup'),
('Fotografia de rua'),
('Desenvolvimento de software'),
('Sistemas operacionais'),
('Literatura'),
('Arquitetura moderna'),
('Linguagens de programação'),
('Marketing digital'),
('Culinária brasileira'),
('Política local'),
('Educação'),
('Filosofia'),
('Redes sociais'),
('Marketing de conteúdo'),
('Política ambiental'),
('Cultura brasileira'),
('História militar'),
('Biografias'),
('Mentoria empresarial'),
('Design de interiores'),
('Cultura japonesa'),
('Cultura geek'),
('Gastronomia molecular'),
('Maternidade'),
('Conservação ambiental'),
('Restaurantes'),
('Música clássica'),
('Terapias alternativas'),
('Relações internacionais'),
('Fotografia de alimentos'),
('Teatro'),
('Comércio exterior'),
('Cultura tradicional'),
('Arte digital'),
('Tecnologia espacial'),
('Esportes de inverno'),
('Gestão de equipe'),
('Viagens culturais'),
('Fotografia'),
('Economia digital'),
('Dança'),
('Investimentos'),
('Arqueologia'),
('Lutas marciais'),
('Cultura escandinava'),
('Tatuagens'),
('LGBTQ+'),
('Tecnologia'),
('Games retro'),
('Inovação'),
('Histórias de viagem'),
('Culinária asiática'),
('Hackathon'),
('Astrologia'),
('Economia colaborativa'),
('Técnicas de estudo'),
('Saúde mental'),
('Cuidados com a pele'),
('Ciclismo'),
('Design de experiência do usuário'),
('Gastronomia internacional'),
('Autoconhecimento'),
('Emoções'),
('Mentoria'),
('Técnicas de vendas'),
('Histórias de superação'),
('Antropologia'),
('Comida orgânica'),
('Gastronomia'),
('Economia solidária'),
('Esportes radicais'),
('Análises políticas'),
('Marketing de relacionamento'),
('Comida artesanal'),
('Bem-estar'),
('Culinária vegana'),
('Comédia'),
('Comida mexicana'),
('Yoga'),
('Tecnologia educacional'),
('Super-heróis'),
('Fotografia de moda'),
('Tecnologia 5G'),
('História medieval'),
('Culinária italiana'),
('Tecnologias emergentes'),
('Astronomia amadora'),
('Startups em tecnologia'),
('Cultura chinesa'),
('Marketing'),
('Esportes'),
('Desenvolvimento de jogos'),
('Fotografia digital'),
('Investimentos imobiliários'),
('Política econômica'),
('Cultura pop coreana'),
('Animais de estimação'),
('Design'),
('Poesia'),
('Cultivo de plantas'),
('Psicoterapia'),
('Empreendendo com tecnologia'),
('Jogos'),
('Bailes de salão'),
('Indústrias criativas'),
('Poesia contemporânea'),
('Sociologia política'),
('História natural'),
('Caminhadas'),
('Esportes urbanos'),
('Cultura'),
('Caminhadas ecológicas'),
('Minimalismo'),
('Liderança jovem'),
('Filmes independentes'),
('Gestão de empresas'),
('Espiritualidade'),
('Cinema alternativo'),
('Startup de tecnologia');